Fix misc e2e and build related issues (#28)
* e2e: add E2E_SKIP and E2E_VERBOSE vars

* e2e: reduce flakeness on CI

Disable PGW+UDP tests for now as they need to be improved to be less
flaky.
Use 3 parallel nodes instead of 8.

* Fix building VPP after changes in upf/

The timestamp checking mechanism was ignoring changes under upf/
because vpp/src/plugins/upf is a symbolic link

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -145,9 +145,21 @@ test:release:
   - sysctl vm.nr_hugepages=0
   - mkdir artifacts junit-output
   # TODO: nightly run without E2E_QUICK
-  # TODO: get rid of E2E_FLAKE_ATTEMPTS. The tests need to be less flaky.
+  # TODO: make UDP tests less flaky and reenable them for PGW
+  # TODO: make tests more stable on CI and remove E2E_FLAKE_ATTEMPTS
+  # TODO: before E2E_FLAKE_ATTEMPTS are removed, detect VPP crashes
+  # and always fail hard in this case, even if any retries could
+  # succeed
   - |
-    if ! make ${TEST_TARGET} E2E_RETEST=y E2E_ARTIFACTS_DIR=$PWD/artifacts E2E_JUNIT_DIR=$PWD/junit-output E2E_PARALLEL=y E2E_PARALLEL_NODES=8 E2E_QUICK=y; then
+    if ! make ${TEST_TARGET} \
+              E2E_RETEST=y \
+              E2E_ARTIFACTS_DIR=$PWD/artifacts \
+              E2E_JUNIT_DIR=$PWD/junit-output \
+              E2E_PARALLEL=y \
+              E2E_PARALLEL_NODES=3 \
+              E2E_QUICK=y \
+              E2E_SKIP='PGW.*counts UDP' \
+              E2E_FLAKE_ATTEMPTS=3; then
       mkdir test-out
       tar -cvzf test-out/vpp-test.tar.gz artifacts || true
       ls -l test-out/
